---
 - name: Check if this is first node
   shell: echo $(hostname -s | sed -e 's/.*\(.\)$/\1/')
   register: result
   ignore_errors: yes
 - name: Starting cluster
   command: pcs cluster enable --all
   when:
      - result.stdout == "1"