---
- name: Install local packages.
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - /tmp/kmod-drbd90-9.0.9-1.el7_4.elrepo.x86_64.rpm
    - /tmp/drbd90-utils-9.3.1-1.el7.elrepo.x86_64.rpm

