  - name: Prepare partition for nfs ha
    copy: src="nfs_ha_partition.sh" dest=/tmp/ mode=0777
  - name: Check if nfs directory exists
    stat:
     path: /dev/mapper/nfsvg-nfslv
    register: nfs_directory
  - name: Execute partitioning script
    command: sh /tmp/nfs_ha_partition.sh
    when: not nfs_directory.stat.exists
